import { type Language } from "./dictionaries";

export const IVA_RATE = 0.16;

export type Tier = {
  key: "arranque" | "crecimiento" | "impacto";
  label: string;
  desc: string;
};

export type Product = {
  id: number;
  slug: string;
  name: string;
  sku: string;
  price: number; // MXN, pre-IVA
  tier: "arranque" | "crecimiento" | "impacto";
  image: string;
  blurb: string;
  includes: string[];
  delivery: string;
};

const IMG = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`;

// 1. Categorías por idioma
export const TIERS: Record<Language, Tier[]> = {
  es: [
    {
      key: "arranque",
      label: "Arranque digital",
      desc: "Lo esencial para lanzar tu marca con una presencia visual sólida y profesional.",
    },
    {
      key: "crecimiento",
      label: "Crecimiento digital",
      desc: "Estrategia y contenido para escalar tu comunicación y ganar audiencia.",
    },
    {
      key: "impacto",
      label: "Impacto premium",
      desc: "Soluciones integrales de alto nivel para marcas que quieren liderar.",
    },
  ],
  en: [
    {
      key: "arranque",
      label: "Digital Starter",
      desc: "The essentials to launch your brand with a solid and professional visual presence.",
    },
    {
      key: "crecimiento",
      label: "Digital Growth",
      desc: "Strategy and content to scale your communication and build an audience.",
    },
    {
      key: "impacto",
      label: "Premium Impact",
      desc: "High-level, comprehensive solutions for brands that want to lead the market.",
    },
  ]
};

// 2. Base de datos de productos por idioma
const PRODUCTS_DB: Record<Language, Product[]> = {
  es: [
    // ---------- Arranque digital ----------
    {
      id: 91,
      slug: "presencia-express",
      name: "Presencia Express",
      sku: "MAG-001",
      price: 3210,
      tier: "arranque",
      image: IMG("1542744173-8e7e53415bb0"),
      blurb: "Un punto de partida ágil para que tu marca aparezca en redes con piezas profesionales listas para publicar.",
      includes: ["4 diseños para post", "2 portadas de destacados", "Paleta base de marca", "Archivos listos para publicar"],
      delivery: "Entrega 100% online en 5 días hábiles",
    },
    {
      id: 92,
      slug: "creativo-inicial",
      name: "Creativo Inicial",
      sku: "MAG-002",
      price: 4280,
      tier: "arranque",
      image: IMG("1611162617474-5b21e879e113"),
      blurb: "Diseño con personalidad para que tu feed empiece a comunicar con coherencia y estilo.",
      includes: ["6 diseños para post y story", "Plantillas editables", "Guía rápida de tono visual", "Archivos listos para publicar"],
      delivery: "Entrega 100% online en 6 días hábiles",
    },
    {
      id: 93,
      slug: "branding-mini",
      name: "Branding Mini",
      sku: "MAG-003",
      price: 6150,
      tier: "arranque",
      image: IMG("1581291518857-4e27b48ff24e"),
      blurb: "La identidad visual mínima viable: colores, tipografías y un kit que te hace reconocible.",
      includes: ["Paleta de colores y tipografías", "Mini kit visual de marca", "2 portadas para redes", "Guía básica de uso"],
      delivery: "Entrega 100% online en 8 días hábiles",
    },
    {
      id: 94,
      slug: "social-starter",
      name: "Social Starter",
      sku: "MAG-004",
      price: 8240,
      tier: "arranque",
      image: IMG("1559028012-481c04fa702d"),
      blurb: "Todo lo necesario para arrancar una estrategia de contenido constante en redes sociales.",
      includes: ["10 diseños para feed", "Calendario editorial de 2 semanas", "Copys optimizados", "Hashtags sugeridos"],
      delivery: "Entrega 100% online en 9 días hábiles",
    },
    {
      id: 95,
      slug: "contenido-visual",
      name: "Contenido Visual",
      sku: "MAG-005",
      price: 11710,
      tier: "arranque",
      image: IMG("1505373877841-8d25f7d46678"),
      blurb: "Producción de contenido creativo que detiene el scroll y conecta con tu audiencia.",
      includes: ["2 videos cortos tipo reel", "8 diseños para feed", "Copys y hashtags", "Archivos listos para publicar"],
      delivery: "Entrega 100% online en 12 días hábiles",
    },
    {
      id: 96,
      slug: "plantillas-pro",
      name: "Plantillas Pro",
      sku: "MAG-006",
      price: 15980,
      tier: "arranque",
      image: IMG("1467232004584-a241de8bcf5d"),
      blurb: "Un sistema de plantillas editables para que publiques con calidad de agencia, tú mismo.",
      includes: ["15 plantillas editables", "Sistema visual de marca", "Set de portadas y highlights", "Tutorial de edición"],
      delivery: "Entrega 100% online en 12 días hábiles",
    },
    {
      id: 97,
      slug: "kit-de-redes",
      name: "Kit de Redes",
      sku: "MAG-007",
      price: 16230,
      tier: "arranque",
      image: IMG("1517048676732-d65bc937f952"),
      blurb: "El paquete completo para dejar tus redes impecables y consistentes desde el primer día.",
      includes: ["Kit visual completo de marca", "20 diseños para feed y story", "Calendario editorial mensual", "Guía de comunicación"],
      delivery: "Entrega 100% online en 14 días hábiles",
    },

    // ---------- Crecimiento digital ----------
    {
      id: 98,
      slug: "imagen-profesional",
      name: "Imagen Profesional",
      sku: "MAG-008",
      price: 8520,
      tier: "crecimiento",
      image: IMG("1556761175-5973dc0f32e7"),
      blurb: "Refinamos la imagen de tu marca para proyectar confianza y profesionalismo.",
      includes: ["Auditoría de imagen actual", "Rediseño de portadas y bio", "8 piezas de feed renovadas", "Recomendaciones de mejora"],
      delivery: "Entrega 100% online en 9 días hábiles",
    },
    {
      id: 99,
      slug: "campana-creativa",
      name: "Campaña Creativa",
      sku: "MAG-009",
      price: 9380,
      tier: "crecimiento",
      image: IMG("1542744095-fcf48d80b0fd"),
      blurb: "Una campaña con concepto, narrativa y piezas pensadas para mover a tu audiencia.",
      includes: ["Concepto creativo de campaña", "10 piezas gráficas", "Guion de 1 video", "Plan de publicación"],
      delivery: "Entrega 100% online en 10 días hábiles",
    },
    {
      id: 100,
      slug: "estrategia-digital-basica",
      name: "Estrategia Digital Básica",
      sku: "MAG-010",
      price: 9900,
      tier: "crecimiento",
      image: IMG("1454165804606-c3d57bc86b40"),
      blurb: "El plan que tu marca necesita para comunicar con dirección y objetivos claros.",
      includes: ["Diagnóstico de redes sociales", "Definición de objetivos", "Guía de tono de comunicación", "Documento estratégico"],
      delivery: "Entrega 100% online en 10 días hábiles",
    },
    {
      id: 103,
      slug: "auditoria-digital",
      name: "Auditoría Digital",
      sku: "MAG-013",
      price: 12280,
      tier: "crecimiento",
      image: IMG("1460925895917-afdab827c52f"),
      blurb: "Analizamos tu presencia digital a fondo y te entregamos un mapa claro de oportunidades.",
      includes: ["Auditoría de 2 redes sociales", "Análisis de contenido", "Análisis de competencia", "Documento con recomendaciones"],
      delivery: "Entrega 100% online en 11 días hábiles",
    },
    {
      id: 101,
      slug: "contenido-pro",
      name: "Contenido Pro",
      sku: "MAG-011",
      price: 13790,
      tier: "crecimiento",
      image: IMG("1486312338219-ce68d2c6f44d"),
      blurb: "Contenido de alto valor: video, diseño y copy trabajando juntos para crecer.",
      includes: ["4 videos cortos tipo reel", "12 diseños para feed", "Copys optimizados", "Calendario editorial mensual"],
      delivery: "Entrega 100% online en 14 días hábiles",
    },
    {
      id: 102,
      slug: "landing-page-basica",
      name: "Landing Page Básica",
      sku: "MAG-012",
      price: 14520,
      tier: "crecimiento",
      image: IMG("1499951360447-b19be8fe80f5"),
      blurb: "Una página de aterrizaje clara y persuasiva para convertir visitas en clientes.",
      includes: ["Diseño de landing de 1 sección larga", "Copy orientado a conversión", "Formulario de contacto", "Optimización para móvil"],
      delivery: "Entrega 100% online en 14 días hábiles",
    },
    {
      id: 104,
      slug: "estrategia-de-publicaciones",
      name: "Estrategia de Publicaciones",
      sku: "MAG-014",
      price: 14800,
      tier: "crecimiento",
      image: IMG("1542435503-956c469947f6"),
      blurb: "Planeamos tu comunicación con un calendario estratégico que mantiene tu marca activa.",
      includes: ["Diagnóstico de redes", "Ideas de publicaciones mensuales", "Guía de tono de comunicación", "Documento estratégico"],
      delivery: "Entrega 100% online en 12 días hábiles",
    },

    // ---------- Impacto premium ----------
    {
      id: 106,
      slug: "estrategia-de-contenidos",
      name: "Estrategia de Contenidos",
      sku: "MAG-016",
      price: 14500,
      tier: "impacto",
      image: IMG("1531403009284-440f080d1e12"),
      blurb: "Un sistema de contenido completo, pensado para posicionar tu marca a largo plazo.",
      includes: ["Estrategia editorial trimestral", "Líneas de contenido y pilares", "Calendario de 3 meses", "Guía de ejecución"],
      delivery: "Entrega 100% online en 15 días hábiles",
    },
    {
      id: 105,
      slug: "branding-digital",
      name: "Branding Digital",
      sku: "MAG-015",
      price: 15900,
      tier: "impacto",
      image: IMG("1551434678-e076c223a692"),
      blurb: "Definimos la identidad visual completa de tu marca con coherencia, estilo y propósito.",
      includes: ["Identidad visual completa", "Sistema de marca para redes", "Kit visual y plantillas", "Manual de uso de marca"],
      delivery: "Entrega 100% online en 16 días hábiles",
    },
    {
      id: 107,
      slug: "video-marketing",
      name: "Video Marketing",
      sku: "MAG-017",
      price: 15900,
      tier: "impacto",
      image: IMG("1573497019940-1c28c88b4f3e"),
      blurb: "El video como motor de crecimiento: contenido dinámico que multiplica tu alcance.",
      includes: ["6 videos cortos tipo reel", "Guiones y storyboard", "Edición profesional", "Estrategia de publicación"],
      delivery: "Entrega 100% online en 16 días hábiles",
    },
    {
      id: 110,
      slug: "funnel-de-conversion",
      name: "Funnel de Conversión",
      sku: "MAG-020",
      price: 18820,
      tier: "impacto",
      image: IMG("1552664730-d307ca884978"),
      blurb: "Diseñamos el recorrido completo para convertir desconocidos en clientes fieles.",
      includes: ["Mapa de funnel completo", "Landing + secuencia de contenido", "Copys para cada etapa", "Plan de medición"],
      delivery: "Entrega 100% online en 18 días hábiles",
    },
    {
      id: 108,
      slug: "presencia-digital-completa",
      name: "Presencia Digital Completa",
      sku: "MAG-018",
      price: 21230,
      tier: "impacto",
      image: IMG("1556745757-8d76bdb6984b"),
      blurb: "Todo tu ecosistema digital cubierto: identidad, contenido, estrategia y producción.",
      includes: ["Branding digital completo", "Contenido mensual integral", "Estrategia y calendario", "Acompañamiento creativo"],
      delivery: "Entrega 100% online en 20 días hábiles",
    },
    {
      id: 111,
      slug: "estrategia-de-marca-avanzada",
      name: "Estrategia de Marca Avanzada",
      sku: "MAG-021",
      price: 24290,
      tier: "impacto",
      image: IMG("1531538606174-0f90ff5dce83"),
      blurb: "Posicionamiento profundo: definimos quién eres, cómo hablas y por qué te eligen.",
      includes: ["Plataforma de marca completa", "Arquitectura de mensajes", "Estrategia de posicionamiento", "Guía maestra de marca"],
      delivery: "Entrega 100% online en 22 días hábiles",
    },
    {
      id: 109,
      slug: "lanzamiento-digital",
      name: "Lanzamiento Digital",
      sku: "MAG-019",
      price: 25680,
      tier: "impacto",
      image: IMG("1556155092-490a1ba16284"),
      blurb: "El paquete definitivo para lanzar o relanzar tu marca con máximo impacto.",
      includes: ["Concepto y estrategia de lanzamiento", "Campaña creativa completa", "Producción de video y diseño", "Plan de medios y medición"],
      delivery: "Entrega 100% online en 25 días hábiles",
    },
  ],

  // ====================== ENGLISH VERSION ======================
  en: [
    // ---------- Digital Starter ----------
    {
      id: 91,
      slug: "express-presence",
      name: "Express Presence",
      sku: "MAG-001",
      price: 3210,
      tier: "arranque",
      image: IMG("1542744173-8e7e53415bb0"),
      blurb: "An agile starting point for your brand to appear on social media with professional, ready-to-publish pieces.",
      includes: ["4 post designs", "2 highlight covers", "Basic brand palette", "Ready-to-publish files"],
      delivery: "100% online delivery in 5 business days",
    },
    {
      id: 92,
      slug: "initial-creative",
      name: "Initial Creative",
      sku: "MAG-002",
      price: 4280,
      tier: "arranque",
      image: IMG("1611162617474-5b21e879e113"),
      blurb: "Design with personality so your feed starts communicating with consistency and style.",
      includes: ["6 post and story designs", "Editable templates", "Quick visual tone guide", "Ready-to-publish files"],
      delivery: "100% online delivery in 6 business days",
    },
    {
      id: 93,
      slug: "mini-branding",
      name: "Mini Branding",
      sku: "MAG-003",
      price: 6150,
      tier: "arranque",
      image: IMG("1581291518857-4e27b48ff24e"),
      blurb: "The minimum viable visual identity: colors, typography, and a kit that makes you recognizable.",
      includes: ["Color palette and typography", "Mini visual brand kit", "2 social media covers", "Basic usage guide"],
      delivery: "100% online delivery in 8 business days",
    },
    {
      id: 94,
      slug: "social-starter",
      name: "Social Starter",
      sku: "MAG-004",
      price: 8240,
      tier: "arranque",
      image: IMG("1559028012-481c04fa702d"),
      blurb: "Everything you need to kick off a consistent content strategy on social media.",
      includes: ["10 feed designs", "2-week editorial calendar", "Optimized copy", "Suggested hashtags"],
      delivery: "100% online delivery in 9 business days",
    },
    {
      id: 95,
      slug: "visual-content",
      name: "Visual Content",
      sku: "MAG-005",
      price: 11710,
      tier: "arranque",
      image: IMG("1505373877841-8d25f7d46678"),
      blurb: "Production of scroll-stopping creative content that connects with your audience.",
      includes: ["2 short reel-style videos", "8 feed designs", "Copy and hashtags", "Ready-to-publish files"],
      delivery: "100% online delivery in 12 business days",
    },
    {
      id: 96,
      slug: "pro-templates",
      name: "Pro Templates",
      sku: "MAG-006",
      price: 15980,
      tier: "arranque",
      image: IMG("1467232004584-a241de8bcf5d"),
      blurb: "An editable template system so you can publish with agency quality yourself.",
      includes: ["15 editable templates", "Visual brand system", "Cover and highlights set", "Editing tutorial"],
      delivery: "100% online delivery in 12 business days",
    },
    {
      id: 97,
      slug: "social-media-kit",
      name: "Social Media Kit",
      sku: "MAG-007",
      price: 16230,
      tier: "arranque",
      image: IMG("1517048676732-d65bc937f952"),
      blurb: "The complete package to leave your social media impeccable and consistent from day one.",
      includes: ["Complete visual brand kit", "20 feed and story designs", "Monthly editorial calendar", "Communication guide"],
      delivery: "100% online delivery in 14 business days",
    },

    // ---------- Digital Growth ----------
    {
      id: 98,
      slug: "professional-image",
      name: "Professional Image",
      sku: "MAG-008",
      price: 8520,
      tier: "crecimiento",
      image: IMG("1556761175-5973dc0f32e7"),
      blurb: "We refine your brand's image to project trust and professionalism.",
      includes: ["Current image audit", "Cover and bio redesign", "8 revamped feed pieces", "Improvement recommendations"],
      delivery: "100% online delivery in 9 business days",
    },
    {
      id: 99,
      slug: "creative-campaign",
      name: "Creative Campaign",
      sku: "MAG-009",
      price: 9380,
      tier: "crecimiento",
      image: IMG("1542744095-fcf48d80b0fd"),
      blurb: "A campaign with concept, narrative, and pieces designed to move your audience.",
      includes: ["Creative campaign concept", "10 graphic pieces", "1 video script", "Publishing plan"],
      delivery: "100% online delivery in 10 business days",
    },
    {
      id: 100,
      slug: "basic-digital-strategy",
      name: "Basic Digital Strategy",
      sku: "MAG-010",
      price: 9900,
      tier: "crecimiento",
      image: IMG("1454165804606-c3d57bc86b40"),
      blurb: "The plan your brand needs to communicate with direction and clear objectives.",
      includes: ["Social media diagnosis", "Objective definition", "Communication tone guide", "Strategic document"],
      delivery: "100% online delivery in 10 business days",
    },
    {
      id: 103,
      slug: "digital-audit",
      name: "Digital Audit",
      sku: "MAG-013",
      price: 12280,
      tier: "crecimiento",
      image: IMG("1460925895917-afdab827c52f"),
      blurb: "We deeply analyze your digital presence and deliver a clear map of opportunities.",
      includes: ["Audit of 2 social networks", "Content analysis", "Competitor analysis", "Recommendations document"],
      delivery: "100% online delivery in 11 business days",
    },
    {
      id: 101,
      slug: "pro-content",
      name: "Pro Content",
      sku: "MAG-011",
      price: 13790,
      tier: "crecimiento",
      image: IMG("1486312338219-ce68d2c6f44d"),
      blurb: "High-value content: video, design, and copy working together to grow.",
      includes: ["4 short reel-style videos", "12 feed designs", "Optimized copy", "Monthly editorial calendar"],
      delivery: "100% online delivery in 14 business days",
    },
    {
      id: 102,
      slug: "basic-landing-page",
      name: "Basic Landing Page",
      sku: "MAG-012",
      price: 14520,
      tier: "crecimiento",
      image: IMG("1499951360447-b19be8fe80f5"),
      blurb: "A clear and persuasive landing page to convert visitors into clients.",
      includes: ["1 long-form landing page design", "Conversion-oriented copy", "Contact form", "Mobile optimization"],
      delivery: "100% online delivery in 14 business days",
    },
    {
      id: 104,
      slug: "publishing-strategy",
      name: "Publishing Strategy",
      sku: "MAG-014",
      price: 14800,
      tier: "crecimiento",
      image: IMG("1542435503-956c469947f6"),
      blurb: "We plan your communication with a strategic calendar that keeps your brand active.",
      includes: ["Social media diagnosis", "Monthly post ideas", "Communication tone guide", "Strategic document"],
      delivery: "100% online delivery in 12 business days",
    },

    // ---------- Premium Impact ----------
    {
      id: 106,
      slug: "content-strategy",
      name: "Content Strategy",
      sku: "MAG-016",
      price: 14500,
      tier: "impacto",
      image: IMG("1531403009284-440f080d1e12"),
      blurb: "A complete content system designed to position your brand long-term.",
      includes: ["Quarterly editorial strategy", "Content pillars and lines", "3-month calendar", "Execution guide"],
      delivery: "100% online delivery in 15 business days",
    },
    {
      id: 105,
      slug: "digital-branding",
      name: "Digital Branding",
      sku: "MAG-015",
      price: 15900,
      tier: "impacto",
      image: IMG("1551434678-e076c223a692"),
      blurb: "We define your brand's complete visual identity with consistency, style, and purpose.",
      includes: ["Complete visual identity", "Social media brand system", "Visual kit and templates", "Brand usage manual"],
      delivery: "100% online delivery in 16 business days",
    },
    {
      id: 107,
      slug: "video-marketing",
      name: "Video Marketing",
      sku: "MAG-017",
      price: 15900,
      tier: "impacto",
      image: IMG("1573497019940-1c28c88b4f3e"),
      blurb: "Video as a growth engine: dynamic content that multiplies your reach.",
      includes: ["6 short reel-style videos", "Scripts and storyboard", "Professional editing", "Publishing strategy"],
      delivery: "100% online delivery in 16 business days",
    },
    {
      id: 110,
      slug: "conversion-funnel",
      name: "Conversion Funnel",
      sku: "MAG-020",
      price: 18820,
      tier: "impacto",
      image: IMG("1552664730-d307ca884978"),
      blurb: "We design the complete journey to turn strangers into loyal clients.",
      includes: ["Complete funnel map", "Landing + content sequence", "Copy for each stage", "Measurement plan"],
      delivery: "100% online delivery in 18 business days",
    },
    {
      id: 108,
      slug: "complete-digital-presence",
      name: "Complete Digital Presence",
      sku: "MAG-018",
      price: 21230,
      tier: "impacto",
      image: IMG("1556745757-8d76bdb6984b"),
      blurb: "Your entire digital ecosystem covered: identity, content, strategy, and production.",
      includes: ["Complete digital branding", "Comprehensive monthly content", "Strategy and calendar", "Creative guidance"],
      delivery: "100% online delivery in 20 business days",
    },
    {
      id: 111,
      slug: "advanced-brand-strategy",
      name: "Advanced Brand Strategy",
      sku: "MAG-021",
      price: 24290,
      tier: "impacto",
      image: IMG("1531538606174-0f90ff5dce83"),
      blurb: "Deep positioning: we define who you are, how you speak, and why they choose you.",
      includes: ["Complete brand platform", "Messaging architecture", "Positioning strategy", "Master brand guide"],
      delivery: "100% online delivery in 22 business days",
    },
    {
      id: 109,
      slug: "digital-launch",
      name: "Digital Launch",
      sku: "MAG-019",
      price: 25680,
      tier: "impacto",
      image: IMG("1556155092-490a1ba16284"),
      blurb: "The ultimate package to launch or relaunch your brand with maximum impact.",
      includes: ["Launch concept and strategy", "Complete creative campaign", "Video and design production", "Media and measurement plan"],
      delivery: "100% online delivery in 25 business days",
    },
  ]
};

export function formatMXN(value: number): string {
  return new Intl.NumberFormat("es-MX", {
    style: "currency",
    currency: "MXN",
    minimumFractionDigits: 2,
  }).format(value);
}

// 3. Funciones Helper Dinámicas por Idioma
export function getProductsByTier(tierKey: Product["tier"], lang: Language): Product[] {
  return PRODUCTS_DB[lang].filter((p) => p.tier === tierKey);
}

export function getProductBySlug(slug: string, lang: Language): Product | undefined {
  return PRODUCTS_DB[lang].find((p) => p.slug === slug);
}